{
 "title": "Unbound",
 "description": "Unbound DNS resolver metrics",
 "tags": [
  "unbound",
  "dns",
  "resolver"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(unbound_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queries",
   "type": "stat",
   "description": "Total number of queries received at the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_queries_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(unbound_queries_total{instance=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Unwanted queries",
   "type": "stat",
   "description": "Total number of queries that were refused or dropped because they failed the access control settings at the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_unwanted_queries_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Unwanted replies",
   "type": "stat",
   "description": "Total number of replies that were unwanted or unsolicited  at the selected time range.\n\nA sharp increase in unwanted traffic indicates a possible spoof run in progress.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_unwanted_replies_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Memory cache size",
   "type": "stat",
   "description": "Max memory in use by caches at the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unbound_memory_caches_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "The number of threads created to serve clients",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(unbound_queries_total{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "heatmap",
   "description": "Query response time in seconds",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(unbound_response_time_seconds_bucket{instance=\"$instance\", le=~\"0.001024|0.002048|0.004096|0.008192|0.016384|0.032768|0.065536|0.131072|0.262144|0.524288|1|2|4|8|16|32|64\"}[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Cache hit/miss ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(unbound_cache_hits_total{instance=\"$instance\"}[$__range]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(increase(unbound_cache_misses_total{instance=\"$instance\"}[$__range]))",
     "legendFormat": "Misses"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Incoming TCP queries",
   "type": "stat",
   "description": "Total number of queries that were made using TCP towards the Unbound server at the selected time range.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_tcp_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Cache Hit %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_cache_hits_total{instance=\"$instance\"}[$__range]))/sum(increase(unbound_queries_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Recursive Replies %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_recursive_replies_total{instance=\"$instance\"}[$__range]))/sum(increase(unbound_queries_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Recursive Queries Median",
   "type": "stat",
   "description": "The median of the time it took to answer queries that needed recursive processing",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "unbound_recursion_time_seconds_median{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Recursive Queries Average",
   "type": "stat",
   "description": "Average time it took to answer queries that needed recursive processing (does not include in-cache requests).",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "unbound_recursion_time_seconds_avg{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "IPv6 queries",
   "type": "stat",
   "description": "Total number of queries that were made using IPv6 towards the Unbound server at the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_ipv6_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Prefetches",
   "type": "stat",
   "description": "Total number of cache prefetches performed",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_prefetches_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Secure answers",
   "type": "stat",
   "description": "Total amount of answers that were secure (AD) at the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(unbound_answers_secure_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Bogus answers",
   "type": "stat",
   "description": "Total amount of answers that were bogus (withheld as SERVFAIL) at the selected time range.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(unbound_answers_bogus{instance=\"$instance\"}[$__interval])"
    }
   ]
  },
  {
   "title": "EDNS OPT queries",
   "type": "stat",
   "description": "Total number of queries that had an EDNS OPT record present at the selected time range.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_edns_present_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Incoming TLS queries",
   "type": "stat",
   "description": "Total number of queries that were made using TLS towards the Unbound server at the selected time range.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_tls_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "EDNS OPT + DNSSEC OK queries",
   "type": "stat",
   "description": "Total number of queries that had an EDNS OPT record with the DO (DNSSEC OK) bit set present at the selected time range.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_edns_DO_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Recursion Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "unbound_recursion_time_seconds_median{instance=\"$instance\"}",
     "legendFormat": "median"
    },
    {
     "expr": "unbound_recursion_time_seconds_avg{instance=\"$instance\"}",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Recursive Replies Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(unbound_recursive_replies_total{instance=\"$instance\"}[5m]))/sum(increase(unbound_queries_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Total Request/Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unbound_queries_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Total answers by rcode",
   "type": "graph",
   "description": "Total number of answers by rcode",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(unbound_answer_rcodes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{rcode}}"
    },
    {
     "expr": "rate(unbound_answers_secure_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Secure (AD)"
    },
    {
     "expr": "rate(unbound_answers_bogus_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Bogus (SERVFAIL)"
    },
    {
     "expr": "rate(unbound_rrset_bogus_total{instance=\"$instance\"}[5m])",
     "legendFormat": "RRset bogus"
    }
   ]
  },
  {
   "title": "Total queries by type",
   "type": "graph",
   "description": "Total number of queries with a given query type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(unbound_query_types_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total queries by opcode",
   "type": "graph",
   "description": "Total number of queries with a given query opcode",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(unbound_query_opcodes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{opcode}}"
    }
   ]
  },
  {
   "title": "Total queries by flag",
   "type": "graph",
   "description": "Total number of queries that had a given flag set in the header",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(unbound_query_flags_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{flag}}"
    },
    {
     "expr": "rate(unbound_query_edns_present_total{instance=\"$instance\"}[1m])",
     "legendFormat": "EDNS OPT"
    },
    {
     "expr": "rate(unbound_query_edns_DO_total{instance=\"$instance\"}[1m])",
     "legendFormat": "DO (DNSSEC OK)"
    }
   ]
  },
  {
   "title": "Total queries by class",
   "type": "graph",
   "description": "Total number of queries with a given query class",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(unbound_query_classes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Prefetch Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(unbound_prefetches_total{instance=\"$instance\"}[5m]))/sum(increase(unbound_queries_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "prefetch"
    }
   ]
  },
  {
   "title": "TCP Req/Sec",
   "type": "graph",
   "description": "Number of the currently held TCP buffers for incoming connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(unbound_query_tcp_total{instance=\"$instance\"}[5m])",
     "legendFormat": "tcp"
    }
   ]
  },
  { "title": "Per thread", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Total queries by thread",
   "type": "graph",
   "description": "Total number of queries handled by each worker thread",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(unbound_queries_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{thread}}"
    }
   ]
  },
  {
   "title": "Total cache prefetches by thread",
   "type": "graph",
   "description": "Total number of cache prefetches performed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(unbound_prefetches_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{thread}}"
    }
   ]
  },
  {
   "title": "Total replies with zero TTL by thread",
   "type": "graph",
   "description": "Total number of replies with ttl zero, because they served an expired cache entry.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(unbound_zero_ttl_responses_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{thread}}"
    }
   ]
  },
  { "title": "Request list", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Request list size",
   "type": "graph",
   "description": "Current size of the request list, including internally generated queries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unbound_request_list_current_all{instance=\"$instance\"}[5m]))",
     "legendFormat": "all"
    },
    {
     "expr": "sum(rate(unbound_request_list_current_user{instance=\"$instance\"}[5m]))",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Total exceeded queries/sec",
   "type": "graph",
   "description": "Number of queries that were dropped because the request list was full",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unbound_request_list_exceeded_total{instance=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total overwritten queries",
   "type": "graph",
   "description": "Total number of requests in the request list that were overwritten by newer entries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unbound_request_list_overwritten_total{instance=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "DNSCrypt",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total successful queries",
     "type": "graph",
     "description": "Total number of queries that were encrypted and successfully decapsulated by dnscrypt",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(unbound_dnscrypt_valid_queries_total{instance=\"$instance\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total certificate requesting queries",
     "type": "graph",
     "description": "Total number of queries that were requesting dnscrypt certificates",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(unbound_dnscrypt_cert_queries_total{instance=\"$instance\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total received cleartext queries",
     "type": "graph",
     "description": "Total number of queries received on dnscrypt port that were cleartext and not a request for certificates",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(unbound_dnscrypt_cleartext_queries_total{instance=\"$instance\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total malformed queries",
     "type": "graph",
     "description": "Total number of requests that were neither cleartext, not valid dnscrypt messages",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(unbound_dnscrypt_malformed_queries_total{instance=\"$instance\"}[5m]))"
      }
     ]
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Cache hits / misses",
   "type": "graph",
   "description": "Hits: total number of queries that were successfully answered using a cache lookup.\n\nMisses: total number of cache queries that needed recursive processing",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unbound_cache_hits_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(irate(unbound_cache_misses_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "graph",
   "description": "Memory in bytes by caches",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "unbound_memory_caches_bytes{instance=\"$instance\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cached entries",
   "type": "graph",
   "description": "The number of cached entries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unbound_msg_cache_count{instance=\"$instance\"}",
     "legendFormat": "msg"
    },
    {
     "expr": "unbound_rrset_cache_count{instance=\"$instance\"}",
     "legendFormat": "rrset"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Modules size",
   "type": "graph",
   "description": "Memory in use by modules",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "unbound_memory_modules_bytes", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "Stream wait buffers size",
   "type": "graph",
   "description": " The number of bytes in the stream wait buffers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(unbound_memory_stream_wait_count{instance=\"$instance\"}[5m])"
    }
   ]
  }
 ]
}